"""add canonical fare layer

Revision ID: 1956ba44f923
Revises: 20260905_0001
Create Date: 2026-09-05 15:11:10.233323
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1956ba44f923"
down_revision: str | Sequence[str] | None = "20260905_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_fares",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column(
            "advance_window",
            sa.Enum(
                "T1",
                "T7",
                "T15",
                "T30",
                "T45",
                "OTHER",
                name="canonical_advance_window",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("flight_identity", sa.String(length=64), nullable=False),
        sa.Column("cabin_class", sa.String(length=40), nullable=False),
        sa.Column("fare_class", sa.String(length=80), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("representative_total_fare", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("minimum_total_fare", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("maximum_total_fare", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("dispersion_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("source_count", sa.Integer(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("has_source_conflict", sa.Boolean(), nullable=False),
        sa.Column("selection_reason", sa.String(length=40), nullable=False),
        sa.Column("method_version", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("dispersion_amount >= 0", name="ck_canonical_dispersion_nonnegative"),
        sa.CheckConstraint("maximum_total_fare >= minimum_total_fare", name="ck_canonical_range"),
        sa.CheckConstraint("minimum_total_fare >= 0", name="ck_canonical_minimum_nonnegative"),
        sa.CheckConstraint("observation_count > 0", name="ck_canonical_observation_count_positive"),
        sa.CheckConstraint(
            "representative_total_fare >= 0", name="ck_canonical_representative_nonnegative"
        ),
        sa.CheckConstraint("source_count > 0", name="ck_canonical_source_count_positive"),
        sa.ForeignKeyConstraint(["collection_run_id"], ["collection_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_run_id",
            "route_id",
            "advance_window",
            "flight_identity",
            "cabin_class",
            "fare_class",
            "currency",
            name="uq_canonical_fare_identity",
        ),
    )
    op.create_index(
        op.f("ix_canonical_fares_advance_window"),
        "canonical_fares",
        ["advance_window"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_fares_collection_run_id"),
        "canonical_fares",
        ["collection_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_fares_flight_identity"),
        "canonical_fares",
        ["flight_identity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_fares_route_id"), "canonical_fares", ["route_id"], unique=False
    )
    op.create_table(
        "canonical_fare_observations",
        sa.Column("canonical_fare_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_total_fare", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["canonical_fare_id"], ["canonical_fares.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["observation_id"], ["fare_observations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("canonical_fare_id", "observation_id"),
        sa.UniqueConstraint("observation_id"),
    )
    op.create_index(
        op.f("ix_canonical_fare_observations_source_id"),
        "canonical_fare_observations",
        ["source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_canonical_fare_observations_source_id"), table_name="canonical_fare_observations"
    )
    op.drop_table("canonical_fare_observations")
    op.drop_index(op.f("ix_canonical_fares_route_id"), table_name="canonical_fares")
    op.drop_index(op.f("ix_canonical_fares_flight_identity"), table_name="canonical_fares")
    op.drop_index(op.f("ix_canonical_fares_collection_run_id"), table_name="canonical_fares")
    op.drop_index(op.f("ix_canonical_fares_advance_window"), table_name="canonical_fares")
    op.drop_table("canonical_fares")
    # ### end Alembic commands ###
