from enum import StrEnum


class SourceType(StrEnum):
    AIRLINE_DIRECT = "AIRLINE_DIRECT"
    OTA = "OTA"
    PUBLIC_DATA = "PUBLIC_DATA"
    FIXTURE = "FIXTURE"


class SourceReviewStatus(StrEnum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    RESTRICTED = "RESTRICTED"
    BLOCKED = "BLOCKED"
    PARSER_CHANGED = "PARSER_CHANGED"
    DISABLED = "DISABLED"


class SourceHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    PARSER_CHANGED = "PARSER_CHANGED"
    DISABLED = "DISABLED"


class DataClass(StrEnum):
    LIVE = "LIVE"
    HISTORICAL = "HISTORICAL"
    SYNTHETIC = "SYNTHETIC"
    RECORDED_DEMO = "RECORDED_DEMO"


class AdvanceWindow(StrEnum):
    T1 = "T1"
    T7 = "T7"
    T15 = "T15"
    T30 = "T30"
    T45 = "T45"
    OTHER = "OTHER"


class RunTrigger(StrEnum):
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"
    BACKFILL = "BACKFILL"
    TEST = "TEST"


class RunStatus(StrEnum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class JobStatus(StrEnum):
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AvailabilityStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    SOLD_OUT = "SOLD_OUT"
    CANCELLED = "CANCELLED"
    NO_RESULT = "NO_RESULT"
    SOURCE_FAILURE = "SOURCE_FAILURE"
    UNKNOWN = "UNKNOWN"


class QualityStatus(StrEnum):
    ELIGIBLE = "ELIGIBLE"
    ELIGIBLE_FLAGGED = "ELIGIBLE_FLAGGED"
    EXCLUDED = "EXCLUDED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class QualityFlag(StrEnum):
    DUPLICATE = "DUPLICATE"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"
    FARE_COMPONENT_MISMATCH = "FARE_COMPONENT_MISMATCH"
    POSSIBLE_OUTLIER = "POSSIBLE_OUTLIER"
    MISSING_FARE = "MISSING_FARE"
    PARSER_ERROR = "PARSER_ERROR"
    UNSUPPORTED_CURRENCY = "UNSUPPORTED_CURRENCY"
    UNSUPPORTED_CABIN = "UNSUPPORTED_CABIN"
    CONNECTING_FLIGHT = "CONNECTING_FLIGHT"
    INCOMPLETE_FLIGHT_IDENTITY = "INCOMPLETE_FLIGHT_IDENTITY"
    UNAPPROVED_SOURCE = "UNAPPROVED_SOURCE"
    UNKNOWN_AIRPORT = "UNKNOWN_AIRPORT"
    ROUTE_MISMATCH = "ROUTE_MISMATCH"
    NEGATIVE_FARE = "NEGATIVE_FARE"
    UNAVAILABLE_FARE = "UNAVAILABLE_FARE"
    INVALID_TRAVEL_DATE = "INVALID_TRAVEL_DATE"
    INVALID_BOOKING_WINDOW = "INVALID_BOOKING_WINDOW"
    DATA_CLASS_MISMATCH = "DATA_CLASS_MISMATCH"
    SOURCE_MISMATCH = "SOURCE_MISMATCH"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class FailureCode(StrEnum):
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    RATE_LIMITED = "RATE_LIMITED"
    ROBOTS_DISALLOWED = "ROBOTS_DISALLOWED"
    TERMS_RESTRICTED = "TERMS_RESTRICTED"
    CAPTCHA_BLOCKED = "CAPTCHA_BLOCKED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    PARSER_CHANGED = "PARSER_CHANGED"
    NO_RESULTS = "NO_RESULTS"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    INVALID_RESPONSE = "INVALID_RESPONSE"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


class PublicationStatus(StrEnum):
    PUBLISHED = "PUBLISHED"
    INSUFFICIENT_COVERAGE = "INSUFFICIENT_COVERAGE"
    PROVISIONAL_BASE = "PROVISIONAL_BASE"
    FAILED = "FAILED"


class AggregationPeriod(StrEnum):
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


class AggregationStatus(StrEnum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INSUFFICIENT_COVERAGE = "INSUFFICIENT_COVERAGE"
    NO_DATA = "NO_DATA"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class ReferenceScope(StrEnum):
    NATIONAL = "NATIONAL"
    ROUTE = "ROUTE"


class ReferenceStatus(StrEnum):
    FINAL = "FINAL"
    PROVISIONAL = "PROVISIONAL"
